USE master
IF EXISTS(SELECT * FROM sys.databases WHERE name='QL_ShopQuanAo')
BEGIN
        DROP DATABASE QL_ShopQuanAo
END
CREATE DATABASE QL_ShopQuanAo
GO
USE QL_ShopQuanAo
GO

CREATE TABLE QUYEN 
(
    MAQUYEN INT IDENTITY NOT NULL,
    TENQUYEN NVARCHAR(50), -- TÊN CÁC NHÓM QUYỀN(ADIMIN,NHÂN VIÊN)
    CONSTRAINT PK_QUYEN PRIMARY KEY (MAQUYEN) --KHÓA CHÍNH
)
CREATE TABLE TAIKHOAN 
(
    MATK CHAR(10) NOT NULL, 
    TENTK VARCHAR(50),
	MATKHAU CHAR(50),
    MAQUYEN INT ,
	--KHÓA CHÍNH
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MATK),
	--KHÓA NGOẠI
	CONSTRAINT FK_TK_QUYEN FOREIGN KEY(MAQUYEN) REFERENCES QUYEN(MAQUYEN)
)
CREATE TABLE THONGTINTAIKHOAN 
(
	MATK CHAR(10) NOT NULL, 
    HOTEN NVARCHAR(50), -- HỌ TÊN
    NGSINH DATE, -- NGÀY SINH
    GTINH NVARCHAR(3),
    NGTAO DATETIME, -- NGÀY TẠO
    EMAIL VARCHAR(50), -- ĐỊA CHỈ EMAIL
    SDT VARCHAR(11), -- SDT
    DCHI NVARCHAR(50), -- ĐỊA CHỈ NHÀ
	TINHTRANG NVARCHAR(50),---ĐANG LÀM ,NGHỈ VIỆC
	--KHÓA CHÍNH
    CONSTRAINT PK_TTTK PRIMARY KEY (MATK),
	--KHÓA NGOẠI
	CONSTRAINT FK_TTTK_TAIKHOAN FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK)
)
CREATE TABLE KHACHHANG 
(
    MAKH VARCHAR(11) NOT NULL, -- sdt 
    DIEMTICHLUY INT,
    CONSTRAINT PK_KH PRIMARY KEY (MAKH)
)
CREATE TABLE NHANVIEN 
(
    MANV VARCHAR(10) NOT NULL,
    MATK CHAR(10) NOT NULL, 
    CONSTRAINT PK_NV PRIMARY KEY (MANV),
    CONSTRAINT FK_NV_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
)
CREATE TABLE LOAISP 
(
    MALSP VARCHAR(6) NOT NULL,
    TENLOAI NVARCHAR(50),
    CONSTRAINT PK_LSP PRIMARY KEY (MALSP)
)
CREATE TABLE DANHMUC 
(
    MADM INT IDENTITY NOT NULL,
    TENDANHMUC NVARCHAR(50),
    CONSTRAINT PK_DMUC PRIMARY KEY (MADM)
)
CREATE TABLE CHITIETDANHMUC 
(
	MADM INT NOT NULL REFERENCES DANHMUC(MADM),
	MALSP VARCHAR(6) NOT NULL REFERENCES LOAISP(MALSP),
	CONSTRAINT PK_CTDM PRIMARY KEY (MADM, MALSP)
)
CREATE TABLE SANPHAM 
(
    MASP INT IDENTITY NOT NULL, -- CREATE AUTO
    TENSP NVARCHAR(MAX), -- TÊN SẢN PHẨM
    SOLUONG INT, -- SỐ LƯỢNG TỒN KHO
    DONGIA FLOAT, -- ĐƠN GIÁ
	HINHANH NVARCHAR(MAX),--HÌNH ẢNH SẢN PHẨM
    NSX NVARCHAR(30), -- NHÀ SẢN XUẤT
    MALSP VARCHAR(6) REFERENCES LOAISP(MALSP),
    CONSTRAINT PK_SP PRIMARY KEY (MASP)
)
CREATE TABLE HOADON 
(
    MAHD INT IDENTITY NOT NULL, -- CREATE AUTO
    NGTAO DATETIME, -- NGÀY TẠO HÓA ĐƠN
    THANHTOAN FLOAT, -- TỔNG (SỐ LƯỢNG * ĐƠN GIÁ)
    TINHTRANG NVARCHAR(50), -- CHƯA THANHTOAN,DATT
    MAKH VARCHAR(11) REFERENCES KHACHHANG(MAKH),
    MANV VARCHAR(10) REFERENCES NHANVIEN(MANV),
    CONSTRAINT PK_HD PRIMARY KEY (MAHD)
)
CREATE TABLE CHITIETHD 
(
    MAHD INT REFERENCES HOADON(MAHD),
    MASP INT REFERENCES SANPHAM(MASP),
    SOLUONG INT, -- SỐ LƯỢNG > 0, số lượng bán
    CONSTRAINT PK_CTHD PRIMARY KEY (MAHD,MASP) 
)

----------------------------------------------------------------------------
--RÀNG BUỘC TOÀN VẸN
----------------------------------------------------------------------------
SET DATEFORMAT DMY

--TABLE TAIKHOAN
ALTER TABLE TAIKHOAN ADD CONSTRAINT uni_TenLoaiTK UNIQUE(TENTK)
GO

--TABLE THONGTINTAIKHOAN
ALTER TABLE THONGTINTAIKHOAN ADD CONSTRAINT chk_GioiTinh CHECK(GTINH IN (N'Nam', N'Nữ'))
ALTER TABLE THONGTINTAIKHOAN ADD CONSTRAINT chk_NgayVaoLam CHECK(NGTAO<=GETDATE())
ALTER TABLE THONGTINTAIKHOAN ADD CONSTRAINT DEF_DC DEFAULT N'TP.HCM' FOR DCHI
ALTER TABLE THONGTINTAIKHOAN ADD CONSTRAINT chk_SDT_NV CHECK(LEN(SDT)=10)
ALTER TABLE THONGTINTAIKHOAN ADD CONSTRAINT UNI_SDT UNIQUE(SDT)
ALTER TABLE THONGTINTAIKHOAN ADD CONSTRAINT UNI_EMAIL UNIQUE(EMAIL)
GO

--TABLE KHACHHANG
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_SDT_KH CHECK(LEN(MAKH)=10)
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_PhanTramGiam CHECK(DIEMTICHLUY>=0 AND DIEMTICHLUY<=50)
GO

--TABLE HOADON
ALTER TABLE CHITIETHD ADD CONSTRAINT chk_SoLuong_CTHD CHECK(SOLUONG>0)
ALTER TABLE HOADON ADD CONSTRAINT chk_ThanhTien_HD CHECK(THANHTOAN>0)
GO

--TABLE DANH MUC
ALTER TABLE DANHMUC ADD CONSTRAINT uni_TenDanhMuc UNIQUE(TENDANHMUC)
GO

--TABLE SANPHAM

ALTER TABLE SANPHAM ADD CONSTRAINT chk_GiaBan CHECK(DONGIA>0)
GO

--Ràng buộc trigger

--Cập nhật thanh toán trên hóa đơn
CREATE TRIGGER CAPNHATTHANHTOAN
ON CHITIETHD
FOR INSERT,UPDATE,DELETE
AS
	BEGIN
	DECLARE @GiamGia MONEY
	
	-- cập nhật số lượng tồn của sản phẩm khi thêm vào 1 CHITIETHD
		UPDATE SANPHAM
		SET SOLUONG = SOLUONG - (SELECT SOLUONG FROM inserted)
				WHERE MASP = (SELECT MASP FROM inserted)
	--cập nhật TỔNG TIỀN sau khi trừ đi ĐIỂM TÍCH LŨY cho KHACHHANG (1 điểm được 2000)
	IF((SELECT DIEMTICHLUY FROM KHACHHANG,HOADON WHERE HOADON.MAKH=KHACHHANG.MAKH AND MAHD =(SELECT MAHD FROM inserted))>0)
	BEGIN
		SET @GiamGia = (SELECT DIEMTICHLUY FROM KHACHHANG,HOADON WHERE HOADON.MAKH=KHACHHANG.MAKH AND MAHD =(SELECT MAHD FROM inserted))*2000
	-- cập nhật TỔNG TIỀN thu được của mỗi CHITIETHD
		UPDATE HOADON
		SET THANHTOAN = (SELECT SUM(CHITIETHD.SOLUONG*SANPHAM.DONGIA)
						FROM CHITIETHD,SANPHAM
						WHERE CHITIETHD.MASP = SANPHAM.MASP AND CHITIETHD.MAHD =(SELECT MAHD FROM inserted) GROUP BY CHITIETHD.MAHD) - @GiamGia
		WHERE MAHD =(SELECT MAHD FROM inserted)
	END
		ELSE
		-- cập nhật TỔNG TIỀN thu được của mỗi CHITIETHD
		UPDATE HOADON
		SET THANHTOAN = (SELECT SUM(CHITIETHD.SOLUONG*SANPHAM.DONGIA)
						FROM CHITIETHD,SANPHAM
						WHERE CHITIETHD.MASP = SANPHAM.MASP AND CHITIETHD.MAHD =(SELECT MAHD FROM inserted) GROUP BY CHITIETHD.MAHD)
		WHERE MAHD =(SELECT MAHD FROM inserted)
	END		
GO
--cập nhật điểm tích lũy khi khách hàng mua sản phẩm trên 500k

CREATE TRIGGER sp_UpdateDiemTL
ON HOADON
AFTER UPDATE
AS
	IF((SELECT THANHTOAN FROM HOADON WHERE MAHD =(SELECT MAHD FROM inserted)) > 500000 
		AND (SELECT TINHTRANG FROM HOADON WHERE MAHD =(SELECT MAHD FROM inserted)) = N'Đã thanh toán')
	BEGIN
		UPDATE KHACHHANG 
		SET DIEMTICHLUY = DIEMTICHLUY + 1
		WHERE MAKH =(SELECT MAKH FROM inserted)
	END
GO


----------------------------------------------------------------------------
--NHẬP DỮ LIỆU
----------------------------------------------------------------------------


--BẢNG QUYỀN
INSERT QUYEN VALUES(N'ADMIN')
INSERT QUYEN VALUES(N'NHÂN VIÊN')

--BẢNG TÀI KHOẢN
CREATE PROC sp_AddTK(
	@MATK CHAR(10) , 
	@TENTK VARCHAR(50),
	@MATKHAU CHAR(50),
    @MAQUYEN INT)

AS 
--KIỂM TRA TRÙNG KHÓA CHÍNH
	IF EXISTS(SELECT * FROM TAIKHOAN WHERE MATK=@MATK)
		RETURN 0
	--THÊM MỚI DỮ LIỆU
	INSERT INTO TAIKHOAN(MATK,TENTK,MATKHAU,MAQUYEN)
	VALUES(@MATK,@TENTK, @MATKHAU, @MAQUYEN)
GO
--mã hash=123
EXEC sp_AddTK '1','ADMIN1','202cb962ac5975b964b7152d234b70','1'
EXEC sp_AddTK '2','ADMIN2','202cb962ac5975b964b7152d234b70','1'
EXEC sp_AddTK '3','NHANVIEN1','202cb962ac5975b964b7152d234b70','2'
EXEC sp_AddTK '4','NHANVIEN2','202cb962ac5975b964b7152d234b70','2'
EXEC sp_AddTK '5','NHANVIEN3','202cb962ac5975b964b7152d234b70','2'
EXEC sp_AddTK '6','NHANVIEN4','202cb962ac5975b964b7152d234b70','2'

--BẢNG THÔNG TIN TÀI KHOẢN
CREATE PROC sp_AddTTTK(
	@MATK CHAR(10) , 
    @HOTEN NVARCHAR(50), -- HỌ TÊN
    @NGSINH DATE, -- NGÀY SINH
    @GTINH NVARCHAR(3),
    @NGTAO DATETIME, -- NGÀY TẠO
    @EMAIL VARCHAR(50), -- ĐỊA CHỈ EMAIL
    @SDT VARCHAR(11), -- SDT
    @DCHI NVARCHAR(50),
	@TINHTRANG NVARCHAR(50))

AS 
--KIỂM TRA TRÙNG KHÓA CHÍNH
	IF EXISTS(SELECT * FROM THONGTINTAIKHOAN WHERE MATK=@MATK)
		RETURN 0
	--THÊM MỚI DỮ LIỆU
	INSERT INTO THONGTINTAIKHOAN(MATK,HOTEN,NGSINH,GTINH,NGTAO,EMAIL,SDT,DCHI,TINHTRANG)
	VALUES(@MATK,@HOTEN,@NGSINH,@GTINH,@NGTAO,@EMAIL,@SDT,@DCHI,@TINHTRANG)
GO

EXEC sp_AddTTTK '1',N'LÊ THÙY NA','17/05/2001',N'Nữ','1/1/2021 07:08:09','nalethuy@gmail.com','0362417182',N'Phú Yên',N'Đang Làm'
EXEC sp_AddTTTK '2',N'TRẦN TRỌNG BÌNH PHƯƠNG','01/01/2001',N'NAM','1/1/2021 07:08:09','phuong@gmail.com','0123456789',N'Đồng Tháp',N'Đang Làm'
EXEC sp_AddTTTK '3',N'TRẦN ĐỨC THẮNG','09/07/2001',N'Nam','1/1/2021 07:08:09','bnguyenva@gmail.com','0345674123',N'Bình Dương',N'Đang Làm'
EXEC sp_AddTTTK '4',N'HUỲNH THU PHƯƠNG','08/07/1999',N'Nữ','1/1/2021 07:08:09','tunu@gmail.com','0312345678',N'Bình Dương',N'Đang Làm'
EXEC sp_AddTTTK '5',N'TẠ MINH TRỰC','05/07/2001',N'Nam','1/1/2021 07:08:09','minhtruc12@gmail.com','0383039079',N'Bình Dương',N'Đang Làm'
EXEC sp_AddTTTK '6',N'VÕ KIỀU MINH HẢI','01/07/1999',N'Nữ','1/1/2021 07:08:09','minhhai2@gmail.com','0961314900',N'Bình Dương',N'Đang Làm'

--BẢNG KHÁCH HÀNG
INSERT KHACHHANG VALUES('0934214565',0)
INSERT KHACHHANG VALUES('0948571923',1)
INSERT KHACHHANG VALUES('0968492918',2)
INSERT KHACHHANG VALUES('0989090761',3)

--BẢNG NHÂN VIÊN
INSERT NHANVIEN VALUES('NV01','3')
INSERT NHANVIEN VALUES('NV02','4')
INSERT NHANVIEN VALUES('NV03','5')
INSERT NHANVIEN VALUES('NV04','6')

-- BẢNG DANH MỤC
INSERT DANHMUC VALUES(N'Áo')
INSERT DANHMUC VALUES(N'Quần' )
INSERT DANHMUC VALUES(N'Váy' )
INSERT DANHMUC VALUES(N'Đầm' )
INSERT DANHMUC VALUES(N'Phụ kiện' )


-- BẢNG LOẠI SP
-- áo
INSERT LOAISP VALUES('LSP01',N'Trễ vai')
INSERT LOAISP VALUES('LSP02',N'Croptop')
INSERT LOAISP VALUES('LSP03',N'Sơ mi')
INSERT LOAISP VALUES('LSP04',N'Hai dây')

-- quần
INSERT LOAISP VALUES('LSP05',N'Quần short')
INSERT LOAISP VALUES('LSP06',N'Quần ống loe')
INSERT LOAISP VALUES('LSP07',N'Quần skinny')
INSERT LOAISP VALUES('LSP08',N'Quần giả váy')

-- váy
INSERT LOAISP VALUES('LSP09',N'Váy tennis')
INSERT LOAISP VALUES('LSP10',N'Váy chữ A')
INSERT LOAISP VALUES('LSP11',N'Váy jeans')
INSERT LOAISP VALUES('LSP12',N'Váy xòe')

-- đầm
INSERT LOAISP VALUES('LSP13',N'Đầm body')
INSERT LOAISP VALUES('LSP14',N'Đầm babydoll')
INSERT LOAISP VALUES('LSP15',N'Đầm trễ vai')
INSERT LOAISP VALUES('LSP16',N'Set')

--Phụ kiện
INSERT LOAISP VALUES('LSP17',N'Mũ')
INSERT LOAISP VALUES('LSP18',N'Túi')
INSERT LOAISP VALUES('LSP19',N'Đồng hồ')
INSERT LOAISP VALUES('LSP20',N'Giày')

CREATE PROC sp_AddSP(
	@TENSP NVARCHAR(MAX), -- TÊN SẢN PHẨM
    @SOLUONG INT, -- SỐ LƯỢNG TỒN KHO
    @DONGIA FLOAT, -- ĐƠN GIÁ
	@HINHANH NVARCHAR(MAX),
    @NSX NVARCHAR(30), -- NHÀ SẢN XUẤT
    @MALSP VARCHAR(6))

AS 
--KIỂM TRA TRÙNG KHÓA CHÍNH
	IF EXISTS(SELECT * FROM SANPHAM WHERE TENSP=@TENSP)
		RETURN 0
	--THÊM MỚI DỮ LIỆU
	INSERT INTO SANPHAM(TENSP,SOLUONG,DONGIA,HINHANH,NSX,MALSP)
	VALUES(@TENSP,@SOLUONG, @DONGIA,@HINHANH, @NSX,@MALSP)
GO
--BẢNG SP
--ÁO
--trễ vai
EXEC sp_AddSP N'Áo trễ vai 1',40,200000,'1.jpn',N'Việt Nam','LSP01'
EXEC sp_AddSP N'Áo trễ vai 2',40,200000,'2.jpn',N'Trung Quốc','LSP01'
EXEC sp_AddSP N'Áo trễ vai 3',40,200000,'3.jpn',N'Hàn Quốc','LSP01'
EXEC sp_AddSP N'Áo trễ vai 4',40,200000,'4.jpn',N'Thái Lan','LSP01'
EXEC sp_AddSP N'Áo trễ vai 5',40,200000,'5.jpn',N'Việt Nam','LSP01'

--áo croptop

EXEC sp_AddSP N'Áo croptop 1',40,200000,'6.jpn',N'Việt Nam','LSP02'
EXEC sp_AddSP N'Áo croptop 2',40,200000,'7.jpn',N'Việt Nam','LSP02'
EXEC sp_AddSP N'Áo croptop 3',40,200000,'8.jpn',N'Việt Nam','LSP02'
EXEC sp_AddSP N'Áo croptop 4',40,200000,'9.jpn',N'Việt Nam','LSP02'
EXEC sp_AddSP N'Áo croptop 5',40,200000,'10.jpn',N'Việt Nam','LSP02'
--áo sơ mi

EXEC sp_AddSP N'Áo sơ mi 1',40,200000,'11.jpn',N'Việt Nam','LSP03'
EXEC sp_AddSP N'Áo sơ mi 2',40,200000,'12.jpn',N'Việt Nam','LSP03'
EXEC sp_AddSP N'Áo sơ mi 3',40,200000,'13.jpn',N'Việt Nam','LSP03'
EXEC sp_AddSP N'Áo sơ mi 4',40,200000,'14.jpn',N'Việt Nam','LSP03'
EXEC sp_AddSP N'Áo sơ mi 5',40,200000,'15.jpn',N'Việt Nam','LSP03'
--hai dây
EXEC sp_AddSP N'Áo hai dây 1',40,200000,'16.jpn',N'Việt Nam','LSP04'
EXEC sp_AddSP N'Áo hai dây 2',40,200000,'17.jpn',N'Việt Nam','LSP04'
EXEC sp_AddSP N'Áo hai dây 3',40,200000,'18.jpn',N'Việt Nam','LSP04'
EXEC sp_AddSP N'Áo hai dây 4',40,200000,'19.jpn',N'Việt Nam','LSP04'
EXEC sp_AddSP N'Áo hai dây 5',40,200000,'20.jpn',N'Việt Nam','LSP04'

--QUẦN
--quần short
EXEC sp_AddSP N'Quần short 1',40,200000,'21.jpn',N'Việt Nam','LSP05'
EXEC sp_AddSP N'Quần short 2',40,200000,'22.jpn',N'Việt Nam','LSP05'
EXEC sp_AddSP N'Quần short 3',40,200000,'23.jpn',N'Việt Nam','LSP05'
EXEC sp_AddSP N'Quần short 4',40,200000,'24.jpn',N'Việt Nam','LSP05'
EXEC sp_AddSP N'Quần short 5',40,200000,'25.jpn',N'Việt Nam','LSP05'
--quần ống loe
EXEC sp_AddSP N'Quần ống loe 1',40,200000,'26.jpn',N'Việt Nam','LSP06'
EXEC sp_AddSP N'Quần ống loe 2',40,200000,'27.jpn',N'Việt Nam','LSP06'
EXEC sp_AddSP N'Quần ống loe 3',40,200000,'28.jpn',N'Việt Nam','LSP06'
EXEC sp_AddSP N'Quần ống loe 4',40,200000,'29.jpn',N'Việt Nam','LSP06'
EXEC sp_AddSP N'Quần ống loe 5',40,200000,'30.jpn',N'Việt Nam','LSP06'
--quần skinny
EXEC sp_AddSP N'Quần skinny 1',40,200000,'31.jpn',N'Việt Nam','LSP07'
EXEC sp_AddSP N'Quần skinny 2',40,200000,'32.jpn',N'Việt Nam','LSP07'
EXEC sp_AddSP N'Quần skinny 3',40,200000,'33.jpn',N'Việt Nam','LSP07'
EXEC sp_AddSP N'Quần skinny 4',40,200000,'34.jpn',N'Việt Nam','LSP07'
EXEC sp_AddSP N'Quần skinny 5',40,200000,'35.jpn',N'Việt Nam','LSP07'
--quẩn giả váy
EXEC sp_AddSP N'Quần giả váy 1',40,200000,'36.jpn',N'Việt Nam','LSP08'
EXEC sp_AddSP N'Quần giả váy 2',40,200000,'37.jpn',N'Việt Nam','LSP08'
EXEC sp_AddSP N'Quần giả váy 3',40,200000,'38.jpn',N'Việt Nam','LSP08'
EXEC sp_AddSP N'Quần giả váy 4',40,200000,'39.jpn',N'Việt Nam','LSP08'
EXEC sp_AddSP N'Quần giả váy 5',40,200000,'40.jpn',N'Việt Nam','LSP08'

--VÁY
--váy bút tennis
EXEC sp_AddSP N'Váy tennis 1',40,200000,'41.jpn',N'Việt Nam','LSP09'
EXEC sp_AddSP N'Váy tennis 2',40,200000,'42.jpn',N'Việt Nam','LSP09'
EXEC sp_AddSP N'Váy tennis 3',40,200000,'43.jpn',N'Việt Nam','LSP09'
EXEC sp_AddSP N'Váy tennis 4',40,200000,'44.jpn',N'Việt Nam','LSP09'
EXEC sp_AddSP N'Váy tennis 5',40,200000,'45.jpn',N'Việt Nam','LSP09'
--váy chữ A
EXEC sp_AddSP N'Váy chữ A 1',40,200000,'46.jpn',N'Việt Nam','LSP10'
EXEC sp_AddSP N'Váy chữ A 2',40,200000,'47.jpn',N'Việt Nam','LSP10'
EXEC sp_AddSP N'Váy chữ A 3',40,200000,'48.jpn',N'Việt Nam','LSP10'
EXEC sp_AddSP N'Váy chữ A 4',40,200000,'49.jpn',N'Việt Nam','LSP10'
EXEC sp_AddSP N'Váy chữ A 5',40,200000,'50.jpn',N'Việt Nam','LSP10'
--váy jeans
EXEC sp_AddSP N'Váy Jeans 1',40,200000,'51.jpn',N'Việt Nam','LSP11'
EXEC sp_AddSP N'Váy Jeans 2',40,200000,'52.jpn',N'Việt Nam','LSP11'
EXEC sp_AddSP N'Váy Jeans 3',40,200000,'53.jpn',N'Việt Nam','LSP11'
EXEC sp_AddSP N'Váy Jeans 4',40,200000,'54.jpn',N'Việt Nam','LSP11'
EXEC sp_AddSP N'Váy Jeans 5',40,200000,'55.jpn',N'Việt Nam','LSP11'
--váy xòe
EXEC sp_AddSP N'Váy xòe 1',40,200000,'56.jpn',N'Việt Nam','LSP12'
EXEC sp_AddSP N'Váy xòe 2',40,200000,'57.jpn',N'Việt Nam','LSP12'
EXEC sp_AddSP N'Váy xòe 3',40,200000,'58.jpn',N'Việt Nam','LSP12'
EXEC sp_AddSP N'Váy xòe 4',40,200000,'59.jpn',N'Việt Nam','LSP12'
EXEC sp_AddSP N'Váy xòe 5',40,200000,'60.jpn',N'Việt Nam','LSP12'

--ĐẦM
--BODY
EXEC sp_AddSP N'Đầm body 1',40,200000,'61.jpn',N'Việt Nam','LSP13'
EXEC sp_AddSP N'Đầm body 2',40,200000,'62.jpn',N'Việt Nam','LSP13'
EXEC sp_AddSP N'Đầm body 3',40,200000,'63.jpn',N'Việt Nam','LSP13'
EXEC sp_AddSP N'Đầm body 4',40,200000,'64.jpn',N'Việt Nam','LSP13'
EXEC sp_AddSP N'Đầm body 5',40,200000,'65.jpn',N'Việt Nam','LSP13'

--baby doll
EXEC sp_AddSP N'Đầm babydoll 1',40,200000,'66.jpn',N'Việt Nam','LSP14'
EXEC sp_AddSP N'Đầm babydoll 2',40,200000,'67.jpn',N'Việt Nam','LSP14'
EXEC sp_AddSP N'Đầm babydoll 3',40,200000,'68.jpn',N'Việt Nam','LSP14'
EXEC sp_AddSP N'Đầm babydoll 4',40,200000,'69.jpn',N'Việt Nam','LSP14'
EXEC sp_AddSP N'Đầm babydoll 5',40,200000,'70.jpn',N'Việt Nam','LSP14'

--đầm trễ vai
EXEC sp_AddSP N'Đầm trễ vai 1',40,200000,'71.jpn',N'Việt Nam','LSP15'
EXEC sp_AddSP N'Đầm trễ vai 2',40,200000,'72.jpn',N'Việt Nam','LSP15'
EXEC sp_AddSP N'Đầm trễ vai 3',40,200000,'73.jpn',N'Việt Nam','LSP15'
EXEC sp_AddSP N'Đầm trễ vai 4',40,200000,'74.jpn',N'Việt Nam','LSP15'
EXEC sp_AddSP N'Đầm trễ vai 5',40,200000,'75.jpn',N'Việt Nam','LSP15'

--set
EXEC sp_AddSP N'Set 1',40,200000,'76.jpn',N'Việt Nam','LSP16'
EXEC sp_AddSP N'Set 2',40,200000,'77.jpn',N'Việt Nam','LSP16'
EXEC sp_AddSP N'Set 3',40,200000,'78.jpn',N'Việt Nam','LSP16'
EXEC sp_AddSP N'Set 4',40,200000,'79.jpn',N'Việt Nam','LSP16'
EXEC sp_AddSP N'Set 5',40,200000,'80.jpn',N'Việt Nam','LSP16'

--Phụ kiện
--mũ
EXEC sp_AddSP N'Mũ lưỡi trai 1',40,200000,'81.jpn',N'Việt Nam','LSP17'
EXEC sp_AddSP N'Mũ lưỡi trai 2',40,250000,'82.jpn',N'Trung Quốc','LSP17'
EXEC sp_AddSP N'Mũ nồi 1',40,200000,'83.jpn',N'Việt Nam','LSP17'
EXEC sp_AddSP N'Mũ nồi 2',40,200000,'84.jpn',N'Hàn Quốc','LSP17'
EXEC sp_AddSP N'Mũ tròn',40,200000,'85.jpn',N'Việt Nam','LSP17'

--túi

EXEC sp_AddSP N'Túi 1',40,200000,'86.jpn',N'Việt Nam','LSP18'
EXEC sp_AddSP N'Túi 2',40,200000,'87.jpn',N'Việt Nam','LSP18'
EXEC sp_AddSP N'Túi 3',40,200000,'88.jpn',N'Việt Nam','LSP18'
EXEC sp_AddSP N'Túi 4',40,200000,'89.jpn',N'Việt Nam','LSP18'
EXEC sp_AddSP N'Túi 5',40,200000,'90.jpn',N'Việt Nam','LSP18'

--đồng hồ
EXEC sp_AddSP N'Đồng hồ 1',40,200000,'91.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Đồng hồ 2',40,200000,'92.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Đồng hồ 3',40,200000,'93.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Đồng hồ 4',40,200000,'94.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Đồng hồ 5',40,200000,'95.jpn',N'Việt Nam','LSP19'

--Giày
EXEC sp_AddSP N'Giày cao gót 1',40,200000,'96.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Giày búp bê',40,200000,'97.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Giày cao gót 2',40,200000,'98.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Giày cao gót 3',40,200000,'99.jpn',N'Việt Nam','LSP19'
EXEC sp_AddSP N'Giày sneaker',40,200000,'100.jpn',N'Việt Nam','LSP19'

select TENSP,TENLOAI from SANPHAM,LOAISP WHERE SANPHAM.MALSP=LOAISP.MALSP

--BẢNG HÓA ĐƠN
	CREATE PROC sp_AddHD(
    @NGTAO DATETIME, -- NGÀY TẠO HÓA ĐƠN
    @THANHTOAN FLOAT, -- TỔNG (SỐ LƯỢNG * ĐƠN GIÁ)
    @TINHTRANG NVARCHAR(50), -- CHƯA THANHTOAN,DATT
    @MAKH VARCHAR(11),
    @MANV VARCHAR(10) )

AS 
	--THÊM MỚI DỮ LIỆU
	INSERT INTO HOADON(NGTAO,THANHTOAN,TINHTRANG,MAKH,MANV)
	VALUES(@NGTAO,@THANHTOAN,@TINHTRANG,@MAKH,@MANV)
GO

EXEC sp_AddHD '08/12/2020','1',N'Đã thanh toán','0934214565','NV01'
EXEC sp_AddHD '08/01/2020','1',N'Đã thanh toán','0948571923','NV02'
EXEC sp_AddHD '08/05/2020','1',N'Đã thanh toán','0968492918','NV03'

--BẢNG CHI TIẾT HÓA ĐƠN
CREATE PROC sp_AddCTHD(
    @MAHD INT,
    @MASP INT,
    @SOLUONG INT)

AS 
	--KIỂM TRA TRÙNG KHÓA CHÍNH
	IF EXISTS(SELECT * FROM CHITIETHD WHERE MASP=@MASP AND MAHD=@MAHD)
		RETURN 0
	--THÊM MỚI DỮ LIỆU
	INSERT INTO CHITIETHD(MAHD,MASP,SOLUONG)
	VALUES(@MAHD,@MASP,@SOLUONG)
GO

EXEC sp_AddCTHD '1','6','1'
EXEC sp_AddCTHD '1','23','1'
EXEC sp_AddCTHD '1','7','1'
EXEC sp_AddCTHD '1','32','1'
EXEC sp_AddCTHD '1','40','1'
EXEC sp_AddCTHD '1','69','1'

EXEC sp_AddCTHD '2','4','1'
EXEC sp_AddCTHD '2','11','1'
EXEC sp_AddCTHD '2','36','1'
EXEC sp_AddCTHD '2','1','1'
EXEC sp_AddCTHD '2','2','1'
EXEC sp_AddCTHD '2','3','1'


EXEC sp_AddCTHD '3','42','1'
EXEC sp_AddCTHD '3','67','1'
EXEC sp_AddCTHD '3','8','1'
EXEC sp_AddCTHD '3','9','1'
EXEC sp_AddCTHD '3','3','1'
EXEC sp_AddCTHD '3','5','1'

SELECT * FROM CHITIETHD
SELECT * FROM HOADON
SELECT * FROM SANPHAM

--Thống kê doanh thu
CREATE PROC up_RevenueStatistics @From Date, @To Date
AS
	SELECT CONVERT(DATE,NGTAO) 'NgayXuatHD', SUM(THANHTOAN) 'ThanhTien'
	FROM HOADON 
	WHERE CONVERT(DATE,NGTAO) BETWEEN @From AND @To 
	GROUP BY CONVERT(DATE,NGTAO)
GO

--Thống kê sản phẩm
CREATE PROC up_ProductStatistics @From Date, @To Date
AS
	SELECT TENSP, SUM(CHITIETHD.SOLUONG) 'TongSoLuong'
	FROM HOADON, CHITIETHD, SANPHAM
	WHERE HOADON.MAHD=CHITIETHD.MAHD AND CHITIETHD.MASP=SANPHAM.MASP
	AND CONVERT(DATE, NGTAO) BETWEEN @From AND @To
	GROUP BY SANPHAM.MASP, TENSP
GO


CREATE PROC sp_ChartSanPham
@nam int
AS
	SELECT TOP 10 TENSP, SUM(CTHD.SOLUONG) SOLUONGBANRA
	FROM HOADON HD JOIN CHITIETHD CTHD 
		ON HD.MAHD = CTHD.MAHD JOIN SANPHAM SP
		ON SP.MASP = CTHD.MASP
	WHERE YEAR(NGTAO) = @nam
	GROUP BY TENSP
	ORDER BY SOLUONGBANRA DESC
GO

CREATE PROC sp_ChartNhanVien
@nam int
AS
	SELECT HOTEN, SUM(THANHTOAN) DOANHTHU
	FROM HOADON HD JOIN NHANVIEN NV
		ON NV.MANV = HD.MANV JOIN THONGTINTAIKHOAN TTTK
		ON TTTK.MATK = NV.MATK
	WHERE YEAR(HD.NGTAO) = @nam
	GROUP BY HOTEN
	ORDER BY DOANHTHU DESC
GO

CREATE PROC sp_ChartDoanhThu
@nam int
AS
	DECLARE @tbDoanhThu TABLE (THANG INT, DOANHTHU FLOAT)
	INSERT @tbDoanhThu
		SELECT m, SUM(THANHTOAN) DOANHTHU
		FROM (SELECT * FROM HOADON WHERE YEAR(NGTAO) = @nam) dtn RIGHT JOIN (
			SELECT m
			FROM (VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12))
			[1 to 12](m)
		) listMonth
			ON MONTH(NGTAO)=listMonth.m
		GROUP BY m
		ORDER BY m
	
	UPDATE @tbDoanhThu SET DOANHTHU = 0 WHERE DOANHTHU IS NULL
	SELECT * FROM @tbDoanhThu
GO
